export const FETCH_PRODUCT_DETAILS = "FETCH_PRODUCT_DETAILS";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";

export const DELETE_PRODUCT_DATA = "DELETE_PRODUCT_DATA";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";